# Generated by Django 4.2.2 on 2023-06-26 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
                ('name', models.CharField(max_length=150)),
                ('section_id', models.IntegerField(blank=True, null=True)),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='product')),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.section')),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
                ('lead_id', models.IntegerField()),
                ('state_id', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='api.user')),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
                ('stage_id', models.CharField(blank=True, max_length=100, null=True)),
                ('deal_id', models.IntegerField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='api.user')),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='api.lead')),
                ('products', models.ManyToManyField(related_name='products', to='api.product')),
            ],
            bases=('api.basemodel',),
        ),
    ]
