# Generated by Django 4.2.2 on 2023-06-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_section_product_lead_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
