# Generated by Django 4.2.2 on 2023-06-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deal',
            name='lead_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='api.lead'),
        ),
    ]
