# Generated by Django 4.2.2 on 2023-06-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_deal_is_paid_alter_deal_lead_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='products',
        ),
        migrations.AddField(
            model_name='deal',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.product'),
        ),
    ]
